version = 0.1

[default]
[default.global.parameters]
stack_name = "daily-nyt"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "daily-nyt"
region = "us-east-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.deploy.parameters]
stack_name = "daily-nyt-prod"
s3_prefix = "daily-nyt-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = []
